import type { CatalogEntry } from "../../../shared/domain.js";

/**
 * DATA -- the app catalog on the Discover screen.
 *
 * Deliberately a static list, not a table. These are public remote MCP servers;
 * they are the same for every company and change only when we ship a new
 * version. Putting them in the database would mean seeding and migrating rows
 * that no user ever edits.
 *
 * Every URL here was verified against a live MCP `initialize` handshake. Paths
 * are NOT guessable -- HubSpot is `/anthropic`, Vercel is the bare host, Zapier
 * is `/api/v1/connect`, Atlassian is `/v2/mcp` -- so each one is recorded
 * exactly as the provider documents it.
 *
 * `auth` records what the provider *requires*, which is not what we can do:
 *   none  -> connect immediately
 *   token -> paste a static key; works today
 *   oauth -> needs a browser redirect flow. Entries with an `integration_key`
 *            have a managed implementation; the rest are marked unavailable
 *            instead of offering a Connect that dead-ends.
 */
type CatalogSeed = Omit<
  CatalogEntry,
  "connected" | "connect_mode" | "availability_message"
>;

const CATALOG: readonly CatalogSeed[] = [
  // ── Managed OAuth ─────────────────────────────────────────────────────
  {
    key: "gmail",
    name: "Gmail",
    category: "Communication",
    description: "Search, read, draft, label, and organize your mail.",
    url: "https://gmailmcp.googleapis.com/mcp/v1",
    auth: "oauth",
    auth_type: "oauth",
    auth_hint: "Sign in with Google. Each account is its own connection.",
    icon: "gmail",
    integration_key: "gmail",
  },

  // ── No credential required ────────────────────────────────────────────
  {
    key: "deepwiki",
    name: "DeepWiki",
    category: "Research",
    description: "Ask questions about any public GitHub repository.",
    url: "https://mcp.deepwiki.com/mcp",
    auth: "none",
    auth_type: "none",
    auth_hint: "No credentials required.",
    icon: null,
  },
  {
    key: "context7",
    name: "Context7",
    category: "Development",
    description: "Up-to-date documentation for any library.",
    url: "https://mcp.context7.com/mcp",
    auth: "none",
    auth_type: "bearer",
    auth_hint: "Optional API key raises the rate limit.",
    icon: null,
  },
  {
    key: "microsoft-learn",
    name: "Microsoft Learn",
    category: "Research",
    description: "Search Microsoft and Azure documentation.",
    url: "https://learn.microsoft.com/api/mcp",
    auth: "none",
    auth_type: "none",
    auth_hint: "No credentials required.",
    // simple-icons dropped the Microsoft mark; fall back to a monogram.
    icon: null,
  },
  {
    key: "cloudflare-docs",
    name: "Cloudflare Docs",
    category: "Research",
    description: "Search Cloudflare product documentation.",
    url: "https://docs.mcp.cloudflare.com/mcp",
    auth: "none",
    auth_type: "none",
    auth_hint: "No credentials required.",
    icon: "cloudflare",
  },

  // ── Static token: works today ─────────────────────────────────────────
  {
    key: "github",
    name: "GitHub",
    category: "Development",
    description: "Repositories, issues, pull requests, and Actions.",
    // The trailing slash matters here.
    url: "https://api.githubcopilot.com/mcp/",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "GitHub personal access token (classic or fine-grained).",
    icon: "github",
  },
  {
    key: "stripe",
    name: "Stripe",
    category: "Business",
    description: "Customers, payments, subscriptions, and invoices.",
    url: "https://mcp.stripe.com",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "Stripe restricted API key — scope it to what agents need.",
    icon: "stripe",
  },
  {
    key: "supabase",
    name: "Supabase",
    category: "Development",
    description: "Database, auth, storage, and edge functions.",
    url: "https://mcp.supabase.com/mcp",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "Supabase personal access token.",
    icon: "supabase",
  },
  {
    key: "cloudflare",
    name: "Cloudflare",
    category: "Development",
    description: "Workers, DNS, KV, R2, and account configuration.",
    url: "https://mcp.cloudflare.com/mcp",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "Cloudflare API token.",
    icon: "cloudflare",
  },
  {
    key: "neon",
    name: "Neon",
    category: "Development",
    description: "Serverless Postgres branches, queries, and projects.",
    url: "https://mcp.neon.tech/mcp",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "Neon API key.",
    icon: "neon",
  },
  {
    key: "datadog",
    name: "Datadog",
    category: "Monitoring",
    description: "Metrics, logs, traces, monitors, and incidents.",
    // Regional: swap the host for EU/AP sites.
    url: "https://mcp.datadoghq.com/api/unstable/mcp-server/mcp",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "Datadog application key. Change the host for non-US1 sites.",
    icon: "datadog",
  },
  {
    key: "perplexity",
    name: "Perplexity",
    category: "Research",
    description: "Web-grounded search and answers.",
    url: "https://api.perplexity.ai/mcp",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "Perplexity API key.",
    icon: "perplexity",
  },
  {
    key: "firecrawl",
    name: "Firecrawl",
    category: "Research",
    description: "Crawl and scrape any site into clean markdown.",
    url: "https://mcp.firecrawl.dev/v2/mcp",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "Firecrawl API key. A keyless tier also works.",
    icon: null,
  },
  {
    key: "tavily",
    name: "Tavily",
    category: "Research",
    description: "Search and extraction built for agents.",
    // The trailing slash matters here.
    url: "https://mcp.tavily.com/mcp/",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "Tavily API key.",
    icon: null,
  },
  {
    key: "exa",
    name: "Exa",
    category: "Research",
    description: "Neural search over the web.",
    url: "https://mcp.exa.ai/mcp",
    auth: "token",
    // Exa is one of two providers that wants a custom header, not a bearer.
    auth_type: "header",
    auth_header_name: "x-api-key",
    auth_hint: "Exa API key, sent as x-api-key.",
    icon: null,
  },
  {
    key: "huggingface",
    name: "Hugging Face",
    category: "Development",
    description: "Models, datasets, and Spaces.",
    url: "https://huggingface.co/mcp",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "Hugging Face access token. Anonymous access also works.",
    icon: "huggingface",
  },
  {
    key: "browserbase",
    name: "Browserbase",
    category: "Development",
    description: "Headless browsers your agents can drive.",
    url: "https://mcp.browserbase.com/mcp",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "Browserbase API key.",
    icon: null,
  },
  {
    key: "paypal",
    name: "PayPal",
    category: "Business",
    description: "Orders, invoices, payouts, and disputes.",
    url: "https://mcp.paypal.com/mcp",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "PayPal access token from client credentials.",
    icon: "paypal",
  },
  {
    key: "zapier",
    name: "Zapier",
    category: "Productivity",
    description: "Thousands of app actions behind one connection.",
    url: "https://mcp.zapier.com/api/v1/connect",
    auth: "token",
    auth_type: "bearer",
    auth_hint: "Zapier connection token from your own MCP endpoint.",
    icon: "zapier",
  },

  // ── OAuth required: not connectable yet ───────────────────────────────
  {
    key: "linear",
    name: "Linear",
    category: "Productivity",
    description: "Issues, projects, cycles, and roadmaps.",
    url: "https://mcp.linear.app/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Linear requires an OAuth sign-in.",
    icon: "linear",
  },
  {
    key: "notion",
    name: "Notion",
    category: "Productivity",
    description: "Pages, databases, and comments.",
    url: "https://mcp.notion.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Notion requires an OAuth sign-in.",
    icon: "notion",
  },
  {
    key: "slack",
    name: "Slack",
    category: "Communication",
    description: "Channels, messages, and search.",
    url: "https://mcp.slack.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Slack requires an OAuth sign-in.",
    // simple-icons removed the Slack mark on trademark grounds.
    icon: null,
  },
  {
    key: "atlassian",
    name: "Jira & Confluence",
    category: "Productivity",
    description: "Issues, boards, sprints, and pages.",
    url: "https://mcp.atlassian.com/v2/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Atlassian requires an OAuth sign-in.",
    icon: "atlassian",
  },
  {
    key: "sentry",
    name: "Sentry",
    category: "Monitoring",
    description: "Errors, traces, and release health.",
    url: "https://mcp.sentry.dev/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Sentry requires an OAuth sign-in.",
    icon: "sentry",
  },
  {
    key: "asana",
    name: "Asana",
    category: "Productivity",
    description: "Tasks, projects, and portfolios.",
    url: "https://mcp.asana.com/sse",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Asana requires an OAuth sign-in.",
    icon: "asana",
  },
  {
    key: "intercom",
    name: "Intercom",
    category: "Communication",
    description: "Conversations, contacts, and help articles.",
    url: "https://mcp.intercom.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Intercom requires an OAuth sign-in.",
    icon: "intercom",
  },
  {
    key: "hubspot",
    name: "HubSpot",
    category: "Business",
    description: "Contacts, deals, and marketing.",
    // Not /mcp -- that path 404s.
    url: "https://mcp.hubspot.com/anthropic",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "HubSpot requires an OAuth sign-in.",
    icon: "hubspot",
  },
  {
    key: "vercel",
    name: "Vercel",
    category: "Development",
    description: "Deployments, projects, and domains.",
    // Bare host -- /mcp 404s.
    url: "https://mcp.vercel.com",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Vercel requires an OAuth sign-in and allowlists clients.",
    icon: "vercel",
  },
  {
    key: "netlify",
    name: "Netlify",
    category: "Development",
    description: "Sites, deploys, and environment variables.",
    url: "https://mcp.netlify.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Netlify requires an OAuth sign-in.",
    icon: "netlify",
  },
  {
    key: "gitlab",
    name: "GitLab",
    category: "Development",
    description: "Repositories, merge requests, and pipelines.",
    url: "https://gitlab.com/api/v4/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "GitLab requires an OAuth sign-in.",
    icon: "gitlab",
  },
  {
    key: "figma",
    name: "Figma",
    category: "Design",
    description: "Files, frames, and design context.",
    url: "https://mcp.figma.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Figma requires an OAuth sign-in.",
    icon: "figma",
  },
  {
    key: "canva",
    name: "Canva",
    category: "Design",
    description: "Designs, brand assets, and exports.",
    url: "https://mcp.canva.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Canva requires an OAuth sign-in.",
    icon: null,
  },
  {
    key: "webflow",
    name: "Webflow",
    category: "Design",
    description: "Sites, CMS collections, and publishing.",
    url: "https://mcp.webflow.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Webflow requires an OAuth sign-in.",
    icon: "webflow",
  },
  {
    key: "wix",
    name: "Wix",
    category: "Design",
    description: "Sites, stores, and bookings.",
    url: "https://mcp.wix.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Wix requires an OAuth sign-in.",
    icon: "wix",
  },
  {
    key: "airtable",
    name: "Airtable",
    category: "Productivity",
    description: "Bases, tables, and records.",
    url: "https://mcp.airtable.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Airtable requires an OAuth sign-in.",
    icon: "airtable",
  },
  {
    key: "monday",
    name: "Monday.com",
    category: "Productivity",
    description: "Boards, items, and updates.",
    url: "https://mcp.monday.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Monday.com requires an OAuth sign-in.",
    icon: null,
  },
  {
    key: "clickup",
    name: "ClickUp",
    category: "Productivity",
    description: "Tasks, docs, and spaces.",
    url: "https://mcp.clickup.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "ClickUp requires an OAuth sign-in.",
    icon: "clickup",
  },
  {
    key: "box",
    name: "Box",
    category: "Storage",
    description: "Files, folders, and metadata.",
    url: "https://mcp.box.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Box requires an OAuth sign-in.",
    icon: "box",
  },
  {
    key: "dropbox",
    name: "Dropbox",
    category: "Storage",
    description: "Files, folders, and sharing.",
    url: "https://mcp.dropbox.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Dropbox requires an OAuth sign-in.",
    icon: "dropbox",
  },
  {
    key: "square",
    name: "Square",
    category: "Business",
    description: "Payments, catalog, and orders.",
    url: "https://mcp.squareup.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Square requires an OAuth sign-in.",
    icon: "square",
  },
  {
    key: "mongodb",
    name: "MongoDB Atlas",
    category: "Development",
    description: "Clusters, collections, and queries.",
    url: "https://mcp.mongodb.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "MongoDB Atlas requires an OAuth sign-in.",
    icon: "mongodb",
  },
  {
    key: "prisma",
    name: "Prisma",
    category: "Development",
    description: "Postgres databases and schema management.",
    url: "https://mcp.prisma.io/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Prisma requires an OAuth sign-in.",
    icon: "prisma",
  },
  {
    key: "posthog",
    name: "PostHog",
    category: "Monitoring",
    description: "Product analytics, flags, and session replays.",
    url: "https://mcp.posthog.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "PostHog requires an OAuth sign-in.",
    icon: "posthog",
  },
  {
    key: "grafana",
    name: "Grafana Cloud",
    category: "Monitoring",
    description: "Dashboards, alerts, and queries.",
    url: "https://mcp.grafana.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Grafana Cloud requires an OAuth sign-in.",
    icon: "grafana",
  },
  {
    key: "algolia",
    name: "Algolia",
    category: "Development",
    description: "Indices, search, and analytics.",
    url: "https://mcp.algolia.com/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Algolia requires an OAuth sign-in.",
    icon: "algolia",
  },
  {
    key: "semgrep",
    name: "Semgrep",
    category: "Development",
    description: "Static analysis findings and rules.",
    url: "https://mcp.semgrep.ai/mcp",
    auth: "oauth",
    auth_type: "none",
    auth_hint: "Semgrep requires an OAuth sign-in.",
    icon: null,
  },

  // ── Always last: the escape hatch ─────────────────────────────────────
  {
    key: "custom",
    name: "Custom server",
    category: "Custom",
    description: "Any MCP server with an http(s) endpoint.",
    url: null,
    auth: "token",
    auth_type: "none",
    auth_hint: "Paste your own endpoint URL.",
    icon: null,
  },
];

export function listCatalog(): readonly CatalogSeed[] {
  return CATALOG;
}

export function findCatalogEntry(key: string): CatalogSeed | null {
  return CATALOG.find((entry) => entry.key === key) ?? null;
}
