/**
 * Core tenancy: a user signs up, names their company, and the company gets a
 * single gateway token. That token is what every AI client uses to reach the
 * aggregated MCP endpoint.
 *
 * Ids are UUIDv4, generated by Postgres via `gen_random_uuid()` (built into
 * pgcrypto, and core since PG 13) so the database stays the single source of
 * truth rather than trusting the app to supply one.
 */
export async function up(knex) {
  // Required for gen_random_uuid() on Postgres 12 and earlier; a no-op after.
  await knex.raw('CREATE EXTENSION IF NOT EXISTS "pgcrypto"');

  await knex.schema.createTable("companies", (table) => {
    table.uuid("id").primary().defaultTo(knex.raw("gen_random_uuid()"));
    table.string("name").notNullable();
    table.string("slug").notNullable().unique();
    // Presented to the user as the credential for https://sirup.gg/mcp
    table.string("gateway_token").notNullable().unique();
    table.timestamps(true, true);
  });

  await knex.schema.createTable("users", (table) => {
    table.uuid("id").primary().defaultTo(knex.raw("gen_random_uuid()"));
    table.string("email").notNullable().unique();
    table.string("password_hash").notNullable();
    table
      .uuid("company_id")
      .nullable()
      .references("id")
      .inTable("companies")
      .onDelete("SET NULL");
    table.timestamps(true, true);

    // Every authenticated request resolves the user's company from this column.
    table.index("company_id", "users_company_id_index");
  });
}

export async function down(knex) {
  await knex.schema.dropTableIfExists("users");
  await knex.schema.dropTableIfExists("companies");
}
