/**
 * Domain entities, shared by the server and the browser.
 *
 * This is the single source of truth for the shapes that cross the wire. The
 * server imports it so its responses are checked against it, and the frontend
 * imports it so its rendering is checked against the same declarations -- a
 * field renamed on one side becomes a compile error on the other.
 */

/** Every primary key is a UUIDv4 generated by Postgres. */
export type Uuid = string;

/** Timestamps cross the wire as ISO 8601 strings. */
export type IsoDateTime = string;

export interface User {
  id: Uuid;
  email: string;
}

export interface Company {
  id: Uuid;
  name: string;
  slug: string;
}

/**
 * A named subset of the company's connections, with its own gateway token.
 *
 * The company owns connections; a profile chooses which to expose. That is
 * what makes "Frontend" and "Ops" serve different tool lists from the same
 * pool of connected accounts.
 */
export interface Profile {
  id: Uuid;
  name: string;
  slug: string;
  /** The credential an MCP client presents for *this* profile. */
  gateway_token: string;
  is_default: boolean;
  /** How many connections are attached. */
  server_count: number;
  /** Tools this profile actually exposes, across its attached servers. */
  tool_count: number;
}

/** How a company authenticates to one upstream MCP server. */
export type AuthType = "none" | "bearer" | "header";

/**
 * What an upstream server *requires*, which is not the same as what we can do.
 *
 * - "none"   — connect immediately, no credential.
 * - "token"  — paste a static API key or PAT. Works today.
 * - "oauth"  — needs a browser authorization-code flow against the provider.
 *              We cannot complete these yet, so the UI says so plainly rather
 *              than offering a Connect button that leads to a dead end.
 */
export type CatalogAuth = "none" | "token" | "oauth";

/** Discovery state of an upstream, as of the last connection attempt. */
export type ServerStatus = "pending" | "connected" | "error";

export interface McpServer {
  id: Uuid;
  name: string;
  /** Tool-name-safe prefix used for namespacing: `gmail__send_email`. */
  slug: string;
  url: string;
  status: ServerStatus;
  status_message: string | null;
  enabled: boolean;
  tool_count: number;
  /**
   * Whether a credential is stored. The credential itself is never serialised
   * to the client -- see `McpServerModel.$formatJson`.
   */
  has_auth: boolean;
  auth_type: AuthType;
  auth_header_name: string | null;
  last_connected_at: IsoDateTime | null;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
  /** Which profiles expose this connection. Present on list endpoints. */
  profile_ids?: Uuid[];
}

/** A JSON Schema object describing a tool's arguments. */
export type JsonSchema = Record<string, unknown>;

export interface McpTool {
  id: Uuid;
  server_id: Uuid;
  /** The name the upstream server knows. */
  name: string;
  /** The name the gateway exposes: `<server slug>__<name>`. */
  namespaced_name: string;
  description: string | null;
  input_schema: JsonSchema | null;
  enabled: boolean;
}

export interface McpServerWithTools extends McpServer {
  tools: McpTool[];
}

/** What crossed the gateway. Written on the hot path of a tool call. */
export type LogMethod = "tools/list" | "tools/call" | "connect" | "refresh";
export type LogStatus = "ok" | "error";

export interface McpLog {
  id: Uuid;
  method: LogMethod | string;
  tool_name: string | null;
  status: LogStatus;
  duration_ms: number | null;
  message: string | null;
  created_at: IsoDateTime;
  /** Null for gateway-level entries, and for logs whose server was deleted. */
  server_name: string | null;
  server_slug: string | null;
}

export interface LogSummary {
  total: number;
  ok: number;
  error: number;
}

/** An entry in the app catalog on the Discover screen. */
export interface CatalogEntry {
  key: string;
  name: string;
  category: string;
  description: string;
  /** Null where a provider has no single public remote endpoint. */
  url: string | null;
  /** What the provider requires. Drives whether Connect is offered. */
  auth: CatalogAuth;
  /** Which auth type to preselect when `auth` is "token". */
  auth_type: AuthType;
  /** Header name when the provider wants a custom header rather than bearer. */
  auth_header_name?: string;
  /** What to paste, e.g. "GitHub personal access token". */
  auth_hint: string;
  /** simple-icons slug for the brand mark, when one exists. */
  icon: string | null;
  connected: boolean;
}
