/**
 * Generates app/src/lib/brandIcons.ts from the catalog.
 *
 * simple-icons ships ~3000 icons. Importing the package into the browser
 * bundle would pull all of them, so this emits a static map containing only
 * the paths the catalog actually references.
 *
 * Usage: npm run gen:icons
 */
import fs from "node:fs";
import * as si from "simple-icons";
import { listCatalog } from "../server/features/mcp-catalog/mcpCatalog.data.js";

interface SimpleIcon {
  title: string;
  path: string;
  hex: string;
}

const slugs = [
  ...new Set(
    listCatalog()
      .map((entry) => entry.icon)
      .filter((slug): slug is string => Boolean(slug)),
  ),
].sort();

const entries: string[] = [];
const missing: string[] = [];

for (const slug of slugs) {
  const key = `si${slug.charAt(0).toUpperCase()}${slug.slice(1)}`;
  const icon = (si as unknown as Record<string, SimpleIcon>)[key];
  if (!icon) {
    missing.push(slug);
    continue;
  }
  entries.push(
    `  ${JSON.stringify(slug)}: {\n` +
      `    title: ${JSON.stringify(icon.title)},\n` +
      `    hex: ${JSON.stringify(`#${icon.hex}`)},\n` +
      `    path: ${JSON.stringify(icon.path)},\n` +
      `  },`,
  );
}

if (missing.length > 0) {
  console.error(`Unknown simple-icons slugs: ${missing.join(", ")}`);
  process.exit(1);
}

const output = `/**
 * Brand marks for the app catalog.
 *
 * GENERATED by scripts/gen-icons.ts -- do not edit by hand.
 * Run \`npm run gen:icons\` after changing the catalog.
 *
 * Only the icons the catalog references are inlined here. Importing
 * simple-icons directly would pull ~3000 paths into the browser bundle.
 */

export interface BrandIcon {
  title: string;
  /** The brand's official colour, used only where colour is allowed. */
  hex: string;
  /** SVG path data on a 24x24 viewBox. */
  path: string;
}

export const BRAND_ICONS: Record<string, BrandIcon> = {
${entries.join("\n")}
};

export function getBrandIcon(slug: string | null | undefined): BrandIcon | null {
  if (!slug) return null;
  return BRAND_ICONS[slug] ?? null;
}
`;

fs.writeFileSync("app/src/lib/brandIcons.ts", output);
console.log(`Wrote app/src/lib/brandIcons.ts with ${entries.length} icons.`);
